import { constVal, buildCommonSetting } from "./const_val.js";

var src = [
    // 新版本nodejs的openssl
    "${srcPath}/third_party/openssl/openssl/crypto/cmac/cmac.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_d2i_fp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_digest.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_dup.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_gentm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_i2d_fp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_int.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_mbstr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_object.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_octet.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_strex.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_strnid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_time.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_type.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_utctm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_utf8.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_verify.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/ameth_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn_mime.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn_moid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn_mstbl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn_pack.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_item_list.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_parse.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/bio_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/bio_ndef.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/d2i_param.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/d2i_pr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/d2i_pu.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/evp_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/f_int.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/f_string.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/i2d_evp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/n_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/nsseq.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/p5_pbe.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/p5_pbev2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/p5_scrypt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/p8_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/t_bitst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/t_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/t_spki.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_dec.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_fre.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_new.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_scn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_typ.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_utl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_algor.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_bignum.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_info.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_int64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_long.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_sig.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_spki.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/x_val.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_bitstr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_sock.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/ossl_core_bio.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_buff.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_lbuf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_nbio.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_null.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_prefix.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bf_readbuff.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_addr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_cb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_dump.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_sock.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_sock2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_acpt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_bio.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_conn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_core.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_dgram.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_fd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_file.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_log.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_mem.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bio/bss_null.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_x931p.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/rsaz_exp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/rsaz_exp_x2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_add.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_asm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_blind.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_const.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_conv.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_ctx.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_depr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_dh.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_div.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_exp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_exp2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_gcd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_gf2m.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_intern.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_kron.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_mod.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_mont.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_mpi.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_mul.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_nist.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_ppc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_prime.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_rand.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_recp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_rsa_fips186_4.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_shift.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_sparc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_sqr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_sqrt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_srp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bn/bn_word.c",
    "${srcPath}/third_party/openssl/openssl/crypto/buffer/buffer.c",
    "${srcPath}/third_party/openssl/openssl/crypto/buffer/buf_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/camellia.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_cbc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_cfb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_ctr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_misc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/camellia/cmll_ofb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cast/c_cfb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cast/c_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cast/c_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cast/c_ofb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cast/c_skey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/chacha/chacha_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_sd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_smime.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_att.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_cd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_dd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_dh.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_ec.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_env.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_ess.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_io.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_kari.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_pwri.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cms/cms_rsa.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_ssl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_api.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_def.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_mall.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_mod.c",
    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf_sap.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/str2key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/xcbc_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/cbc_cksm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/cbc_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/cfb_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/cfb64ede.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/cfb64enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/des_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ecb_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ecb3_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/fcrypt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/fcrypt_b.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ncbc_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ofb_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ofb64ede.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/ofb64enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/pcbc_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/qud_cksm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/rand_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/des/set_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_ameth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_check.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_depr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_group_params.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_kdf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_pmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_rfc5114.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_ossl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_pmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_vrf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_ameth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_check.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_depr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_init.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_list.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_openssl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_rdrand.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_table.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_asnmth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_cipher.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_dh.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_digest.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_dsa.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_eckey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_pkmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_rand.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/tb_rsa.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_all.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_cnf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_ctrl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_dyn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/engine/eng_fat.c",
    "${srcPath}/third_party/openssl/openssl/crypto/err/err_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/err/err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/err/err_all.c",
    "${srcPath}/third_party/openssl/openssl/crypto/err/err_all_legacy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/err/err_blocks.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/bio_ok.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/c_allc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/c_alld.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/cmeth_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/ctrl_params_translate.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/dh_ctrl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/dh_support.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/digest.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/dsa_ctrl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_aes.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_aes_cbc_hmac_sha1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_aes_cbc_hmac_sha256.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_aria.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_bf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_camellia.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_cast.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_chacha20_poly1305.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_des.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_des3.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_idea.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_null.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_old.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_rc2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_rc4.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_rc4_hmac_md5.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_rc5.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_seed.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_sm4.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/e_xcbc_d.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/ec_ctrl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/ec_support.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/encode.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_cnf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_fetch.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_pbe.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_rand.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_utils.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/exchange.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/kdf_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/kdf_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/kem.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/keymgmt_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/keymgmt_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_blake2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_md4.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_md5.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_md5_sha1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_mdc2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_ripemd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_sha.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/legacy_wp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/m_null.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/m_sigver.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/mac_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/mac_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/names.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_dec.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_legacy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_open.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_seal.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_verify.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p5_crpt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/p5_crpt2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/pbe_scrypt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/pmeth_check.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/pmeth_gn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/pmeth_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/signature.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/asymcipher.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/bio_b64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/bio_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/evp/bio_md.c",
    "${srcPath}/third_party/openssl/openssl/crypto/idea/i_cbc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/idea/i_cfb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/idea/i_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/idea/i_ofb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/idea/i_skey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/kdf/kdf_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/lhash/lh_stats.c",
    "${srcPath}/third_party/openssl/openssl/crypto/lhash/lhash.c",
    "${srcPath}/third_party/openssl/openssl/crypto/md4/md4_dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/md4/md4_one.c",
    "${srcPath}/third_party/openssl/openssl/crypto/md5/md5_dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/md5/md5_one.c",
    "${srcPath}/third_party/openssl/openssl/crypto/md5/md5_sha1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/mdc2/mdc2_one.c",
    "${srcPath}/third_party/openssl/openssl/crypto/mdc2/mdc2dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/cbc128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/ccm128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/cfb128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/ctr128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/cts128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/gcm128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/ocb128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/ofb128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/siv128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/wrap128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/modes/xts128.c",
    "${srcPath}/third_party/openssl/openssl/crypto/objects/obj_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/objects/obj_xref.c",
    "${srcPath}/third_party/openssl/openssl/crypto/objects/o_names.c",
    "${srcPath}/third_party/openssl/openssl/crypto/objects/obj_dat.c",
    "${srcPath}/third_party/openssl/openssl/crypto/objects/obj_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_asn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_cl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_ext.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_http.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_srv.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/ocsp_vfy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ocsp/v3_ocsp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_all.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_info.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_oth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_pk8.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_x509.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_xaux.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pem/pvkfmt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_attr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_doit.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_mime.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pk7_smime.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pkcs7err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/bio_pk7.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_add.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_asn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_attr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_crpt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_crt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_decr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_init.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_kiss.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_mutl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_npas.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_p8d.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_p8e.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_sbag.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/p12_utl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/pkcs12/pk12err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/poly1305/poly1305.c",
    "${srcPath}/third_party/openssl/openssl/crypto/poly1305/poly1305_ppc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/property_string.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/defn_cache.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/property.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/property_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/property_parse.c",
    "${srcPath}/third_party/openssl/openssl/crypto/property/property_query.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/prov_seed.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_deprecated.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_egd.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/rand_pool.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rand/randfile.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc2/rc2_cbc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc2/rc2_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc2/rc2_skey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc2/rc2cfb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc2/rc2ofb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc4/rc4_skey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rc4/rc4_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ripemd/rmd_dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ripemd/rmd_one.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_sp800_56b_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_x931.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_x931g.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_ameth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_chk.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_crpt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_depr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_mp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_mp_names.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_none.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_oaep.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_ossl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_pk1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_pmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_pss.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_saos.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_schemes.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/rsa/rsa_sp800_56b_check.c",
    "${srcPath}/third_party/openssl/openssl/crypto/seed/seed_cbc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/seed/seed_cfb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/seed/seed_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/seed/seed_ofb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/seed/seed.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/keccak1600.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha_ppc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha1_one.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha1dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha3.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha256.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sha/sha512.c",
    "${srcPath}/third_party/openssl/openssl/crypto/siphash/siphash.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm2/sm2_crypt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm2/sm2_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm2/sm2_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm2/sm2_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm3/legacy_sm3.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm3/sm3.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sm4/sm4.c",
    "${srcPath}/third_party/openssl/openssl/crypto/srp/srp_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/srp/srp_vfy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/stack/stack.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_init.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_register.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_result.c",
    "${srcPath}/third_party/openssl/openssl/crypto/store/store_strings.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_conf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_req_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_req_utils.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_rsp_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_rsp_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_rsp_utils.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_rsp_verify.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ts/ts_verify_ctx.c",
    "${srcPath}/third_party/openssl/openssl/crypto/txt_db/txt_db.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ui/ui_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ui/ui_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ui/ui_null.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ui/ui_openssl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ui/ui_util.c",
    "${srcPath}/third_party/openssl/openssl/crypto/whrlpool/wp_block.c",
    "${srcPath}/third_party/openssl/openssl/crypto/whrlpool/wp_dgst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509name.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509rset.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509spki.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509type.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/by_dir.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/by_file.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/by_store.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_cache.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_data.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_map.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_node.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/pcy_tree.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_crl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_req.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_x509.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_addr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_admis.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_akeya.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_akid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_asid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_bcons.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_bitst.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_conf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_cpols.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_crld.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_enum.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_extku.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_genn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_ia5.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_info.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_int.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_ist.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_ncons.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_pci.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_pcia.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_pcons.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_pku.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_pmaps.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_purp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_san.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_skid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_sxnet.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_tlsf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_utf8.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3_utl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/v3err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_all.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_attrib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_crl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_exten.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_name.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_pubkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_req.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_x509.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_x509a.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_att.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_cmp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_d2.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_def.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_ext.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_lu.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_obj.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_r2x.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_req.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_set.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_trust.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_txt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_v3.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_vfy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_vpm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509cset.c",
    "${srcPath}/third_party/openssl/openssl/crypto/initthread.c",
    "${srcPath}/third_party/openssl/openssl/crypto/init.c",
    "${srcPath}/third_party/openssl/openssl/crypto/info.c",
    "${srcPath}/third_party/openssl/openssl/crypto/getenv.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ex_data.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ebcdic.c",
    "${srcPath}/third_party/openssl/openssl/crypto/der_writer.c",
    "${srcPath}/third_party/openssl/openssl/crypto/uid.c",
    "${srcPath}/third_party/openssl/openssl/crypto/trace.c",
    "${srcPath}/third_party/openssl/openssl/crypto/threads_win.c",
    "${srcPath}/third_party/openssl/openssl/crypto/threads_pthread.c",
    "${srcPath}/third_party/openssl/openssl/crypto/threads_none.c",
    "${srcPath}/third_party/openssl/openssl/crypto/threads_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/sparse_array.c",
    "${srcPath}/third_party/openssl/openssl/crypto/self_test_core.c",
    "${srcPath}/third_party/openssl/openssl/crypto/punycode.c",
    "${srcPath}/third_party/openssl/openssl/crypto/provider_predefined.c",
    "${srcPath}/third_party/openssl/openssl/crypto/provider_core.c",
    "${srcPath}/third_party/openssl/openssl/crypto/provider_conf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/provider_child.c",
    "${srcPath}/third_party/openssl/openssl/crypto/provider.c",
    "${srcPath}/third_party/openssl/openssl/crypto/passphrase.c",
    "${srcPath}/third_party/openssl/openssl/crypto/params_from_text.c",
    "${srcPath}/third_party/openssl/openssl/crypto/params_dup.c",
    "${srcPath}/third_party/openssl/openssl/crypto/params.c",
    "${srcPath}/third_party/openssl/openssl/crypto/param_build_set.c",
    "${srcPath}/third_party/openssl/openssl/crypto/param_build.c",
    "${srcPath}/third_party/openssl/openssl/crypto/packet.c",
    "${srcPath}/third_party/openssl/openssl/crypto/o_time.c",
    "${srcPath}/third_party/openssl/openssl/crypto/o_str.c",
    "${srcPath}/third_party/openssl/openssl/crypto/o_init.c",
    "${srcPath}/third_party/openssl/openssl/crypto/o_fopen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/o_dir.c",
    "${srcPath}/third_party/openssl/openssl/crypto/mem_sec.c",
    "${srcPath}/third_party/openssl/openssl/crypto/mem_clr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/mem.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/ssl3_record.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/ssl3_record_tls13.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/tls_pad.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/dtls1_bitmap.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/rec_layer_d1.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/rec_layer_s3.c",
    "${srcPath}/third_party/openssl/openssl/ssl/record/ssl3_buffer.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem_clnt.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem_dtls.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem_lib.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem_quic.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/statem_srvr.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/extensions.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/extensions_clnt.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/extensions_cust.c",
    "${srcPath}/third_party/openssl/openssl/ssl/statem/extensions_srvr.c",
    "${srcPath}/third_party/openssl/openssl/ssl/tls_srp.c",
    "${srcPath}/third_party/openssl/openssl/ssl/tls13_enc.c",
    "${srcPath}/third_party/openssl/openssl/ssl/bio_ssl.c",
    "${srcPath}/third_party/openssl/openssl/ssl/d1_lib.c",
    "${srcPath}/third_party/openssl/openssl/ssl/d1_msg.c",
    "${srcPath}/third_party/openssl/openssl/ssl/d1_srtp.c",
    //"${srcPath}/third_party/openssl/openssl/ssl/ktls.c",
    "${srcPath}/third_party/openssl/openssl/ssl/methods.c",
    "${srcPath}/third_party/openssl/openssl/ssl/pqueue.c",
    "${srcPath}/third_party/openssl/openssl/ssl/s3_cbc.c",
    "${srcPath}/third_party/openssl/openssl/ssl/s3_enc.c",
    "${srcPath}/third_party/openssl/openssl/ssl/s3_lib.c",
    "${srcPath}/third_party/openssl/openssl/ssl/s3_msg.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_asn1.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_cert.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_ciph.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_conf.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_err.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_err_legacy.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_init.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_lib.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_mcnf.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_quic.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_rsa.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_rsa_legacy.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_sess.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_stat.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_txt.c",
    "${srcPath}/third_party/openssl/openssl/ssl/ssl_utst.c",
    "${srcPath}/third_party/openssl/openssl/ssl/t1_enc.c",
    "${srcPath}/third_party/openssl/openssl/ssl/t1_lib.c",
    "${srcPath}/third_party/openssl/openssl/ssl/t1_trce.c",
    "${srcPath}/third_party/openssl/openssl/ssl/tls_depr.c",
    "${srcPath}/third_party/openssl/openssl/providers/prov_running.c",
    "${srcPath}/third_party/openssl/openssl/providers/baseprov.c",
    "${srcPath}/third_party/openssl/openssl/providers/defltprov.c",
    "${srcPath}/third_party/openssl/openssl/providers/legacyprov.c",
    "${srcPath}/third_party/openssl/openssl/providers/nullprov.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/bio_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/capabilities.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/digest_to_nid.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/provider_ctx.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/provider_err.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/provider_seeding.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/provider_util.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/securitycheck.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/securitycheck_default.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/securitycheck_fips.c",
    "${srcPath}/third_party/openssl/openssl/providers/fips/fipsprov.c",
    "${srcPath}/third_party/openssl/openssl/providers/fips/fips_entry.c",
    "${srcPath}/third_party/openssl/openssl/providers/fips/self_test.c",
    "${srcPath}/third_party/openssl/openssl/providers/fips/self_test_kats.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/asymciphers/rsa_enc.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/asymciphers/sm2_enc.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha1_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_ccm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_ccm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_gcm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_gcm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_ocb.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_ocb_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_siv.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_siv_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_wrp.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_xts.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_xts_fips.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aes_xts_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria_ccm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria_ccm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria_gcm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria_gcm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_aria_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_blowfish.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_blowfish_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_camellia.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_camellia_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_cast5.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_cast5_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_chacha20.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_chacha20_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_chacha20_poly1305.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_cts.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_des.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_des_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_desx.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_desx_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_idea.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_idea_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_null.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc2.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc2_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc4.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc4_hmac_md5.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc4_hmac_md5_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_rc4_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_seed.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_seed_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_sm4.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_sm4_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_common.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_default.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_default_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_wrap.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/cipher_tdes_wrap_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_block.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_ccm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_ccm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_gcm.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_gcm_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/ciphers/ciphercommon_hw.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/blake2s_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/digestcommon.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/md4_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/md5_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/md5_sha1_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/mdc2_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/null_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/ripemd_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/sha2_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/sha3_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/sm3_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/wp_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/blake2_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/digests/blake2b_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_der2key.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_epki2pki.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_msblob2key.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_pem2der.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_pvk2key.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/decode_spki2typespki.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/encode_key2blob.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/encode_key2ms.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/encode_key2text.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/endecoder_common.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/exchange/dh_exch.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/exchange/ecdh_exch.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/exchange/ecx_exch.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/exchange/kdf_exch.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/hkdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/kbkdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/krb5kdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/pbkdf1.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/pbkdf2.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/pbkdf2_fips.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/pkcs12kdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/scrypt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/sshkdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/sskdf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/tls1_prf.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kem/rsa_kem.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/dh_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/dsa_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/ec_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/ecx_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/kdf_legacy_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/mac_legacy_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/keymgmt/rsa_kmgmt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/poly1305_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/siphash_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/blake2b_mac.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/blake2s_mac.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/cmac_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/gmac_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/hmac_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/macs/kmac_prov.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/seed_src.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/test_rng.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/crngt.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/drbg.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/drbg_ctr.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/drbg_hash.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/drbg_hmac.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/seeding/rand_cpu_x86.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/seeding/rand_tsc.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/rands/seeding/rand_unix.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/storemgmt/file_store.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/storemgmt/file_store_any2obj.c",
    "${srcPath}/third_party/openssl/openssl/crypto/context.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecx_s390x.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve25519.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_ameth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_check.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_curve.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_cvt.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_deprecated.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_kmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_mult.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_oct.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_pmeth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec_print.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec2_oct.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ec2_smpl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecdh_kdf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecdh_ossl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecdsa_ossl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecdsa_sign.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecdsa_vrf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/eck_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_mont.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_nist.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_nistputil.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_nistz256.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_oct.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_ppc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_s390x_nistp.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecp_smpl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecx_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecx_key.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/ecx_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/curve448.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/curve448_tables.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/eddsa.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/f_generic.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/scalar.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ec/curve448/arch_64/f_impl64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_asn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_client.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_ctx.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_hdr.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_http.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_msg.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_protect.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_server.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_status.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_util.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cmp/cmp_vfy.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_dsa_key.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_sm2_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_sm2_key.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_rsa_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_rsa_key.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_ecx_key.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_ec_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_ec_key.c",
    "${srcPath}/third_party/openssl/openssl/providers/common/der/der_dsa_sig.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_digests_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_dsa_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_ec_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_ecx_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_rsa_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_sm2_gen.c",
    "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/der/der_wrap_gen.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_backend.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_dh.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_key_generate.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_key_validate.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_params.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_params_generate.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ffc/ffc_params_validate.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/encode_decode/encode_key2any.c",
    "${srcPath}/third_party/openssl/openssl/crypto/core_algorithm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/core_namemap.c",
    "${srcPath}/third_party/openssl/openssl/crypto/core_fetch.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/decoder_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/decoder_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/decoder_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/decoder_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/encoder_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/encoder_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/encoder_meth.c",
    "${srcPath}/third_party/openssl/openssl/crypto/encode_decode/encoder_pkey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/async/async.c",
    "${srcPath}/third_party/openssl/openssl/crypto/async/async_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/async/async_wait.c",
    "${srcPath}/third_party/openssl/openssl/crypto/async/arch/async_posix.c",
    "${srcPath}/third_party/openssl/openssl/crypto/hmac/hmac.c",
    "${srcPath}/third_party/openssl/openssl/crypto/asn1_dsa.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aria/aria.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_b64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_log.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_oct.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_policy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_prn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_sct.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_sct_ctx.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_vfy.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ct/ct_x509v3.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/dsa_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/ecdsa_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/eddsa_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/mac_legacy_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/rsa_sig.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/signature/sm2_sig.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ctype.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_cbc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_cfb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_core.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_ige.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_misc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_ofb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_wrap.c",
    "${srcPath}/third_party/openssl/openssl/crypto/aes/aes_x86core.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bf/bf_cfb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bf/bf_ecb.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bf/bf_enc.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bf/bf_ofb64.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bf/bf_skey.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cpuid.c",
    "${srcPath}/third_party/openssl/openssl/providers/implementations/kdfs/x942kdf.c",
    "${srcPath}/third_party/openssl/openssl/crypto/crmf/crmf_asn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/crmf/crmf_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/crmf/crmf_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/crmf/crmf_pbm.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cpt_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_openssl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_win32.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_dl.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_dlfcn.c",
    "${srcPath}/third_party/openssl/openssl/crypto/dso/dso_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_afalg_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_capi.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_capi_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_dasync.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_dasync_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_loader_attic_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_ossltest.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_ossltest_err.c",
    "${srcPath}/third_party/openssl/openssl/engines/e_padlock.c",
    "${srcPath}/third_party/openssl/openssl/crypto/bsearch.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cversion.c",
    "${srcPath}/third_party/openssl/openssl/crypto/cryptlib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/http/http_client.c",
    "${srcPath}/third_party/openssl/openssl/crypto/http/http_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/http/http_lib.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ess/ess_asn1.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ess/ess_err.c",
    "${srcPath}/third_party/openssl/openssl/crypto/ess/ess_lib.c",

// 老版openssl
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_enum.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_gentm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_i2d_fp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_int.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_mbstr.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_object.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_octet.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_print.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_strnid.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_time.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_type.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_utctm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_utf8.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn_pack.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_lib.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/asn1_par.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/f_enum.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/f_int.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/f_string.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_dec.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_enc.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_fre.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_new.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_typ.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/tasn_utl.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/time_support.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_bitstr.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_bool.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_d2i_fp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/asn1/a_dup.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/base64/base64.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/file.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/hexdump.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/pair.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/printf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/socket.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/socket_helper.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/bio_mem.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/connect.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bio/fd.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bn_extra/bn_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bn_extra/convert.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/buf/buf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bytestring/cbs.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bytestring/unicode.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bytestring/asn1_compat.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bytestring/ber.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/bytestring/cbb.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/chacha/chacha.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_rc2.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_rc4.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_tls.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/tls_cbc.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/cipher_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/derive_key.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_aesccm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_aesctrhmac.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_aesgcmsiv.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_chacha20poly1305.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cipher_extra/e_null.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cmac/cmac.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/conf/conf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/curve25519/spake25519.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dh/params.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dh/check.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dh/dh_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/digest_extra/digest_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/dsa/dsa.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/ec_extra/ec_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/ecdh_extra/ecdh_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/ecdsa_extra/ecdsa_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/engine/engine.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/err/err.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_ed25519.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_ed25519_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_rsa.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_rsa_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/pbkdf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/print.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/scrypt.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/sign.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/digestsign.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/evp_ctx.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_dsa_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_ec.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/evp/p_ec_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/is_fips.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/hkdf/hkdf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/hrss/hrss.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/lhash/lhash.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/obj/obj_xref.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/obj/obj.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_xaux.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_all.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_info.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_lib.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_oth.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_pk8.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_pkey.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pem/pem_x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pkcs7_x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pkcs7/pkcs7.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pkcs8/pkcs8_x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pkcs8/p5_pbev2.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pkcs8/pkcs8.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/poly1305/poly1305_vec.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/poly1305/poly1305.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/poly1305/poly1305_arm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/pool/pool.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rand_extra/windows.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rand_extra/deterministic.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rand_extra/forkunsafe.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rand_extra/fuchsia.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rand_extra/rand_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rc4/rc4.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rsa_extra/rsa_print.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/rsa_extra/rsa_asn1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/stack/stack.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/asn1_gen.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/by_dir.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/by_file.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/i2d_pr.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/rsa_pss.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_crl.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_req.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/t_x509a.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_algor.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_all.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_attrib.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_crl.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_exten.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_info.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_name.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_pkey.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_pubkey.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_req.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_sig.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_spki.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_val.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x_x509a.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_att.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_cmp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_d2.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_def.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_ext.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_lu.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_obj.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_r2x.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_req.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_set.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_trs.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_txt.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_v3.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_vfy.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509_vpm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509cset.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509name.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509rset.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/x509spki.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/a_digest.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/a_sign.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/a_strex.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/a_verify.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509/algorithm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_pku.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_pmaps.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_prn.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_purp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_skey.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_sxnet.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_utl.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_cache.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_data.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_lib.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_map.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_node.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/pcy_tree.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_akey.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_akeya.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_alt.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_bcons.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_bitst.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_conf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_cpols.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_crld.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_enum.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_extku.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_genn.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_ia5.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_info.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_int.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_lib.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_ncons.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_ocsp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_pci.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_pcia.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/x509v3/v3_pcons.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/thread_win.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/cpu-intel.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/crypto.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/ex_data.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/mem.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/refcount_c11.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/refcount_lock.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/thread.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/thread_pthread.c",
//    "${srcPath}/third_party/openssl/openssl/ssl/d1_srtp.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/dtls_method.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/dtls_record.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/handoff.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/handshake.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/handshake_client.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/handshake_server.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/s3_both.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/s3_lib.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/s3_pkt.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_aead_ctx.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_asn1.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_buffer.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_cert.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_cipher.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_file.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_key_share.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_lib.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_privkey.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_session.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_stat.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_transcript.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_versions.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/ssl_x509.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/t1_enc.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/t1_lib.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls_method.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls_record.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls13_both.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls13_client.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls13_enc.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/tls13_server.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/bio_ssl.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/d1_both.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/d1_lib.cc",
//    "${srcPath}/third_party/openssl/openssl/ssl/d1_pkt.cc",
//    "${srcPath}/third_party/openssl/openssl/third_party/fiat/curve25519.c",
//    "${srcPath}/third_party/openssl/openssl/third_party/fiat/p256.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/bn.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/bytes.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/cmp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/ctx.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/div.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/div_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/exponentiation.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/gcd.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/gcd_extra.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/generic.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/jacobi.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/montgomery.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/montgomery_inv.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/mul.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/prime.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/random.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/rsaz_exp.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/shift.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/sqrt.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/add.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/aes/mode_wrappers.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/aes/aes.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/aes/key_wrap.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/cipher/cipher.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/cipher/e_aes.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/cipher/e_des.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/cipher/aead.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/des/des.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/digest/digest.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/digest/digests.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/simple.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/simple_mul.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/util.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/wnaf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/ec.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/ec_key.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/ec_montgomery.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/felem.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/oct.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/p224-64.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/p256-x86_64.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ec/scalar.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ecdh/ecdh.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/ecdsa/ecdsa.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/hmac/hmac.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/md4/md4.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/md5/md5.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/polyval.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/cbc.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/ccm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/cfb.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/ctr.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/gcm.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/modes/ofb.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rand/urandom.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rand/ctrdrbg.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rand/rand.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rsa/rsa.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rsa/rsa_impl.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rsa/blinding.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/rsa/padding.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/self_check/self_check.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/sha/sha256.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/sha/sha512.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/sha/sha1.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/sha/sha1-altivec.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/tls/kdf.c",
//    "${srcPath}/third_party/openssl/openssl/crypto/fipsmodule/bn/asm/x86_64-gcc.c",
//    "${srcPath}/third_party/openssl/openssl/err_data.c",
];
var json = [{
    "var":[
        {"sdkPath":constVal.sdkPath},
        {"clangPath":constVal.clangPath},
        {"srcPath":constVal.srcPath},
        {"ndkIncludePath":constVal.ndkIncludePath},
        {"ndkBinPath":constVal.ndkBinPath},
        {"targetDir": constVal.targetDir},
        {"sysroot": constVal.sysroot},
    ],
    "compile":{
        "ccompiler":"${clangPath}/clang.exe",
        "cppcompiler":"${clangPath}/clang++.exe",
            
        "include":[
            ...constVal.includePaths,
            "${srcPath}/linux",
            "${srcPath}/third_party/openssl",
            "${srcPath}/third_party/openssl/openssl",
            "${srcPath}/third_party/openssl/openssl/include",
            "${srcPath}/third_party/openssl/openssl/providers/common/include",
            "${srcPath}/third_party/openssl/openssl/providers/implementations/include",
            "${srcPath}/third_party/openssl/openssl/crypto",
            //"${srcPath}/third_party/openssl/config/archs/VC-WIN64A/no-asm/providers/common/include",
            "${srcPath}/third_party/openssl/config/archs/VC-WIN32/no-asm/providers/common/include",
            "${srcPath}/third_party/zlib",
        ],
        "prebuildSrc":[
            "${srcPath}/third_party/openssl/openssl/crypto/hrss/hrss.c",
        ],
        "src":src,
        "cmd":[
            "-std=c++11",
            "-fms-extensions",
            "-D_GNU_SOURCE",
            "-DHAVE_CONFIG_H",
            "-DOS_LINUX_FOR_WIN",
            "-DL_ENDIAN",
            //"-DOPENSSL_CPUID_OBJ",
            "-DOPENSSL_BN_ASM_PART_WORDS",
            //"-DDSO_WIN32",
            "-DOPENSSL_NO_ASM",
            "-DOPENSSL_NO_KTLS=1",
        ],
        "objdir":"${srcPath}/out/tmp/openssl/${targetDir}",
        "outdir":"${srcPath}/out/${targetDir}",
        "target":"libopenssl.a",
        "beginLibs":[
        ],
        "linkerCmd":[],
        "endLibs":[
        ],
        "linker":"${ndkBinPath}/llvm-ar.exe"
    }
}];

if ("x86_64-linux-guneabi" == constVal.target) { // ARM64
    json[0].compile.cmd.push("-D_M_X64=100");
}

buildCommonSetting(json);
